### ISSUE TITLE
[Snake] 뱀 머리<->꼬리 렌더링 순서 변경

### ISSUE THREAD

**Issue by kysha91** [jihyun-s/SampleProject#16]

**Comment by jihyun-s** [comment]
뱀이 자기자신한테 부딪치는 경우 뱀머리의 혀가 잘리는 현상이 있으므로 렌더링 순서를 변경하기로 함. 
기존 : 뱀 머리->몸통앞 -> 몸통뒤
수정 후 :  몸통앞 -> 몸통뒤 -> 뱀 머리
수정 완료
